#!/bin/sh
# Configure the Pi as a WiFi access point (WPA2) from /etc/discodb2/discodb2.env.
#
# Idempotent: regenerates hostapd + dnsmasq config and the static-IP dropin from
# the env file every run. Run by install.sh and re-runnable on the Pi.
#
# DESIGN §8: Pi = WiFi AP + WPA2 (open WiFi rejected). Fixed IP (e.g.
# 192.168.4.1). This is the DEPLOYMENT layer — never backend code.
#
# POSIX sh.
set -eu

ENV_FILE=/etc/discodb2/discodb2.env
[ -r "$ENV_FILE" ] && . "$ENV_FILE"

AP_IFACE="${AP_IFACE:-wlan0}"
AP_SSID="${AP_SSID:-discodb2}"
AP_PASSPHRASE="${AP_PASSPHRASE:-changeme-discodb2}"
AP_CHANNEL="${AP_CHANNEL:-6}"
AP_COUNTRY="${AP_COUNTRY:-FR}"
AP_ADDR="${AP_ADDR:-192.168.4.1}"
AP_NETMASK="${AP_NETMASK:-255.255.255.0}"
AP_DHCP_START="${AP_DHCP_START:-192.168.4.50}"
AP_DHCP_END="${AP_DHCP_END:-192.168.4.150}"
# ONE .local name across dnsmasq + Avahi (default "discodb" -> discodb.local).
MDNS_HOSTNAME="${MDNS_HOSTNAME:-discodb}"

log() { echo "[ap-setup] $*"; }

# WPA2 requires an 8..63 char passphrase. Refuse open/short — DESIGN §8.
plen=$(printf %s "$AP_PASSPHRASE" | wc -c | tr -d ' ')
if [ "$plen" -lt 8 ] || [ "$plen" -gt 63 ]; then
    log "ERROR: AP_PASSPHRASE must be 8..63 chars (got $plen). Open WiFi is rejected."
    exit 1
fi
if [ "$AP_PASSPHRASE" = "changeme-discodb2" ]; then
    log "WARNING: AP_PASSPHRASE is still the default. Change it in $ENV_FILE!"
fi

# ── hostapd ──────────────────────────────────────────────────────────────────
# hw_mode=g + 2.4GHz channel keeps us compatible with the USB dongle and Pi 1B+.
cat > /etc/hostapd/hostapd.conf <<EOF
# Generated by discodb2 ap-setup.sh — DO NOT EDIT (edit $ENV_FILE and re-run).
country_code=$AP_COUNTRY
interface=$AP_IFACE
driver=nl80211
ssid=$AP_SSID
hw_mode=g
channel=$AP_CHANNEL
ieee80211d=1
wmm_enabled=1
auth_algs=1
ignore_broadcast_ssid=0
# WPA2-PSK only (no WPA1, no open).
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=$AP_PASSPHRASE
EOF
chmod 600 /etc/hostapd/hostapd.conf

# Point the hostapd service at our config (Debian default reads this var).
if [ -f /etc/default/hostapd ]; then
    sed -i 's|^#\?DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd
else
    echo 'DAEMON_CONF="/etc/hostapd/hostapd.conf"' > /etc/default/hostapd
fi

# ── dnsmasq (DHCP only; we are not a DNS resolver for the world) ──────────────
mkdir -p /etc/dnsmasq.d
cat > /etc/dnsmasq.d/discodb2.conf <<EOF
# Generated by discodb2 ap-setup.sh — DO NOT EDIT (edit $ENV_FILE and re-run).
interface=$AP_IFACE
bind-interfaces
# DHCP pool. 12h lease is plenty for a phone/laptop in the car.
dhcp-range=$AP_DHCP_START,$AP_DHCP_END,$AP_NETMASK,12h
# Hand the Pi itself as gateway + DNS so http://$AP_ADDR:PORT just works.
dhcp-option=3,$AP_ADDR
dhcp-option=6,$AP_ADDR
# Resolve the friendly name to the Pi for the captive-portal-free UX. SAME name
# as Avahi publishes (MDNS_HOSTNAME -> <name>.local) so there is ONE host name.
address=/$MDNS_HOSTNAME.local/$AP_ADDR
EOF

# ── static IP on the AP interface (no DHCP client on wlanX) ───────────────────
# We use systemd-networkd-agnostic dhcpcd dropin (default on Pi OS Lite).
if [ -f /etc/dhcpcd.conf ]; then
    # Strip any previous discodb2 block, then append a fresh one.
    sed -i '/# >>> discodb2 AP >>>/,/# <<< discodb2 AP <<</d' /etc/dhcpcd.conf
    cat >> /etc/dhcpcd.conf <<EOF
# >>> discodb2 AP >>>
interface $AP_IFACE
static ip_address=$AP_ADDR/24
nohook wpa_supplicant
# <<< discodb2 AP <<<
EOF
fi

# Make sure the regulatory domain is set so the radio will actually beacon.
if command -v iw >/dev/null 2>&1; then
    iw reg set "$AP_COUNTRY" 2>/dev/null || true
fi

# Free the radio: on a Pi the onboard wlan0 is claimed by wpa_supplicant by
# default; for AP-on-onboard we mask the client supplicant on that iface.
rfkill unblock wlan 2>/dev/null || true

log "AP configured: ssid='$AP_SSID' iface=$AP_IFACE addr=$AP_ADDR channel=$AP_CHANNEL country=$AP_COUNTRY"
log "hostapd: /etc/hostapd/hostapd.conf  dnsmasq: /etc/dnsmasq.d/discodb2.conf"
